[package]
name = "db"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
core_types = { path = "../core_types", features = [ "ssr" ] }

surrealdb.workspace = true
eyre.workspace = true
tracing.workspace = true
