[package]
name = "db"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
core_types = { path = "../core_types", features = [ "ssr" ] }

serde.workspace = true
surrealdb.workspace = true
eyre.workspace = true
tracing.workspace = true

surrealdb-migrations = { version = "1.5" }
