
name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-trusted-public-keys = surrealdb.cachix.org-1:rbm7Qs+s36pxbfk9jhIa5HRld6gZ63koZz1h/9sSxaA=
            extra-trusted-substituters = https://surrealdb.cachix.org"
      - name: Use Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Containerize & Deploy to Fly
        run: nix build ".#container" -L && docker load < result && flyctl deploy --local-only --detach -i site-server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
