
name: CI

on:
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-trusted-public-keys = surrealdb.cachix.org-1:rbm7Qs+s36pxbfk9jhIa5HRld6gZ63koZz1h/9sSxaA=
            extra-trusted-substituters = https://surrealdb.cachix.org"
      - name: Verify flake inputs
        uses: DeterminateSystems/flake-checker-action@main
      - name: Use Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build dependencies
        run: nix build ".#deps-only" -L
      - name: Run checks
        run: nix flake check -L
      - name: Build server package
        run: nix build ".#container" -L

  fly-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Validate fly.io config
        run: flyctl config validate
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
